# 과제 1번

In [100]:
class Set:
    def __init__(self, member=[]):
        self.member = member
        self.result =  {i for i in self.member}
            
    def append(self, a):
        if a in member:
            return self.result
        else:
            temp = member.append(a)
            return {i for i in temp}
    def delete(self, a):
        if a in self.result:
            self.temp = member.remove(a)
            self.dele = {i for i in self.temp}
            return self.dele
        else:
            return "없어요!"
           
    def union(self, s2):
        self.mem = self.member + s2.member 
        self.union = {i for i in self.mem}
        return self.union
    
    def difference(self, s2):
        self.dif = []
        for i in self.mem:
            if i not in s2.member:
                self.dif.append(i)
            self.difference = {i for i in self.dif}                
        return self.difference    

    def intersection(self, s2):
        self.inter = []
        for i in self.member:
            if i in s2.member:
                self.inter.append(i)
            self.intersection = {i for i in self.inter} 
        return self.intersection    


    def __add__(self, other):
        return self.union
       
    def __sub__(self, other):
        return self.difference
       
    def __truediv__(self,other):
        return self.intersection

In [102]:
a = Set([1, 2, 3])
b = Set([2, 3, 4])
c = a.union(b)
print(c)

d = a.difference(b)

print(d)

e = a.intersection(b)

print(e)
c = a + b
print(c)
d = a - b
print(d)
e = a / b
print(e)


{1, 2, 3, 4}
{1}
{2, 3}
{1, 2, 3, 4}
{1}
{2, 3}


# 과제 2번

In [65]:
class person:
    def __init__(self, name, age, department):
        self.name = name
        self.age = age
        self.department = department
    def get_name(self):
        return self.name
    
class Student(person):
    def __init__(self, name, age, department, s_id, GPA ):
        person.__init__(self, name, age, department)
        self.s_id = s_id
        self.GPA = GPA
    def reg_advisor(self, prof):
        self.advisor = prof
    def print_info(self):
        print("제 이름은", self.name, ", 나이는", self.age, ", 학과는", self.department, ",지도교수님은",self.advisor.name, "입니다")

class Professor(person):
    def __init__(self, name, age, department, position, laboratory):
        person.__init__(self, name, age, department)
        self.position = position
        self.laboratory = laboratory
        self.student = []
    def reg_student(self, student):
        self.student.append(student)
    def print_info(self):
        print("제 이름은", self.name, ", 나이는", self.age, ", 학과는", self.department, ",지도학생은", end=" ")
        for i in self.student:
            print(i.name, end=", ")
        print("입니다")
        
        
        

In [66]:
stu1 = Student('Kim', 30, 'Computer', 20001234, 4.5)
stu2 = Student('Lee', 22, 'Computer',20101234, 0.5)
prof1 = Professor('Lee', 55, 'Computer','Full', 'KLE')

stu1.reg_advisor(prof1)

stu2.reg_advisor(prof1)
prof1.reg_student(stu1)
prof1.reg_student(stu2)
stu1.print_info()
stu2.print_info()
prof1.print_info()


제 이름은 Kim , 나이는 30 , 학과는 Computer ,지도교수님은 Lee 입니다
제 이름은 Lee , 나이는 22 , 학과는 Computer ,지도교수님은 Lee 입니다
제 이름은 Lee , 나이는 55 , 학과는 Computer ,지도학생은 Kim, Lee, 입니다


# 과제3

In [175]:
import numpy as np
x1 = np.array([0,0])
x2 = np.array([0,1])
x3 = np.array([1,0])
x4 = np.array([1,1])

for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            for a in range(1,10):
                for c in range(1,10):
                    for d in range(1,10):
                        w = np.array([[i,j],[k,a]])
                        b = np.array([c,d])
                        if np.argmax(np.dot(w,x1)-b) == 1 and np.argmax(np.dot(w,x2)-b) ==1 and np.argmax(np.dot(w,x3)-b) ==1 and np.argmax(np.dot(w,x4)-b) ==0 and (np.dot(w,x4)-b)[0] != (np.dot(w,x4)-b)[1]:
                            print(w,b)


[[3 3]
 [1 1]] [4 1]
[[3 3]
 [1 1]] [5 2]
[[3 3]
 [1 1]] [6 3]
[[3 3]
 [1 1]] [7 4]
[[3 3]
 [1 1]] [8 5]
[[3 3]
 [1 1]] [9 6]
[[3 4]
 [1 1]] [5 1]
[[3 4]
 [1 1]] [6 2]
[[3 4]
 [1 1]] [7 3]
[[3 4]
 [1 1]] [8 4]
[[3 4]
 [1 1]] [9 5]
[[3 4]
 [1 2]] [4 1]
[[3 4]
 [1 2]] [5 2]
[[3 4]
 [1 2]] [6 3]
[[3 4]
 [1 2]] [7 4]
[[3 4]
 [1 2]] [8 5]
[[3 4]
 [1 2]] [9 6]
[[3 5]
 [1 1]] [6 1]
[[3 5]
 [1 1]] [7 2]
[[3 5]
 [1 1]] [8 3]
[[3 5]
 [1 1]] [9 4]
[[3 5]
 [1 2]] [5 1]
[[3 5]
 [1 2]] [6 2]
[[3 5]
 [1 2]] [7 3]
[[3 5]
 [1 2]] [8 4]
[[3 5]
 [1 2]] [9 5]
[[3 5]
 [1 3]] [4 1]
[[3 5]
 [1 3]] [5 2]
[[3 5]
 [1 3]] [6 3]
[[3 5]
 [1 3]] [7 4]
[[3 5]
 [1 3]] [8 5]
[[3 5]
 [1 3]] [9 6]
[[3 6]
 [1 1]] [7 1]
[[3 6]
 [1 1]] [8 2]
[[3 6]
 [1 1]] [9 3]
[[3 6]
 [1 2]] [6 1]
[[3 6]
 [1 2]] [7 2]
[[3 6]
 [1 2]] [8 3]
[[3 6]
 [1 2]] [9 4]
[[3 6]
 [1 3]] [5 1]
[[3 6]
 [1 3]] [6 2]
[[3 6]
 [1 3]] [7 3]
[[3 6]
 [1 3]] [8 4]
[[3 6]
 [1 3]] [9 5]
[[3 6]
 [1 4]] [4 1]
[[3 6]
 [1 4]] [5 2]
[[3 6]
 [1 4]] [6 3]
[[3 6]
 [1 4]

[[5 5]
 [1 1]] [6 1]
[[5 5]
 [1 1]] [7 1]
[[5 5]
 [1 1]] [7 2]
[[5 5]
 [1 1]] [8 1]
[[5 5]
 [1 1]] [8 2]
[[5 5]
 [1 1]] [8 3]
[[5 5]
 [1 1]] [9 2]
[[5 5]
 [1 1]] [9 3]
[[5 5]
 [1 1]] [9 4]
[[5 5]
 [1 2]] [6 1]
[[5 5]
 [1 2]] [7 1]
[[5 5]
 [1 2]] [7 2]
[[5 5]
 [1 2]] [8 2]
[[5 5]
 [1 2]] [8 3]
[[5 5]
 [1 2]] [9 3]
[[5 5]
 [1 2]] [9 4]
[[5 5]
 [1 3]] [6 1]
[[5 5]
 [1 3]] [7 2]
[[5 5]
 [1 3]] [8 3]
[[5 5]
 [1 3]] [9 4]
[[5 5]
 [2 1]] [6 1]
[[5 5]
 [2 1]] [7 1]
[[5 5]
 [2 1]] [7 2]
[[5 5]
 [2 1]] [8 2]
[[5 5]
 [2 1]] [8 3]
[[5 5]
 [2 1]] [9 3]
[[5 5]
 [2 1]] [9 4]
[[5 5]
 [2 2]] [5 1]
[[5 5]
 [2 2]] [6 1]
[[5 5]
 [2 2]] [6 2]
[[5 5]
 [2 2]] [7 2]
[[5 5]
 [2 2]] [7 3]
[[5 5]
 [2 2]] [8 3]
[[5 5]
 [2 2]] [8 4]
[[5 5]
 [2 2]] [9 4]
[[5 5]
 [2 2]] [9 5]
[[5 5]
 [2 3]] [5 1]
[[5 5]
 [2 3]] [6 2]
[[5 5]
 [2 3]] [7 3]
[[5 5]
 [2 3]] [8 4]
[[5 5]
 [2 3]] [9 5]
[[5 5]
 [3 1]] [6 1]
[[5 5]
 [3 1]] [7 2]
[[5 5]
 [3 1]] [8 3]
[[5 5]
 [3 1]] [9 4]
[[5 5]
 [3 2]] [5 1]
[[5 5]
 [3 2]] [6 2]
[[5 5]
 [3 2]

[[6 5]
 [1 1]] [7 1]
[[6 5]
 [1 1]] [8 1]
[[6 5]
 [1 1]] [8 2]
[[6 5]
 [1 1]] [9 1]
[[6 5]
 [1 1]] [9 2]
[[6 5]
 [1 1]] [9 3]
[[6 5]
 [1 2]] [7 1]
[[6 5]
 [1 2]] [8 1]
[[6 5]
 [1 2]] [8 2]
[[6 5]
 [1 2]] [9 2]
[[6 5]
 [1 2]] [9 3]
[[6 5]
 [1 3]] [7 1]
[[6 5]
 [1 3]] [8 2]
[[6 5]
 [1 3]] [9 3]
[[6 5]
 [2 1]] [6 1]
[[6 5]
 [2 1]] [7 1]
[[6 5]
 [2 1]] [7 2]
[[6 5]
 [2 1]] [8 1]
[[6 5]
 [2 1]] [8 2]
[[6 5]
 [2 1]] [8 3]
[[6 5]
 [2 1]] [9 2]
[[6 5]
 [2 1]] [9 3]
[[6 5]
 [2 1]] [9 4]
[[6 5]
 [2 2]] [6 1]
[[6 5]
 [2 2]] [7 1]
[[6 5]
 [2 2]] [7 2]
[[6 5]
 [2 2]] [8 2]
[[6 5]
 [2 2]] [8 3]
[[6 5]
 [2 2]] [9 3]
[[6 5]
 [2 2]] [9 4]
[[6 5]
 [2 3]] [6 1]
[[6 5]
 [2 3]] [7 2]
[[6 5]
 [2 3]] [8 3]
[[6 5]
 [2 3]] [9 4]
[[6 5]
 [3 1]] [6 1]
[[6 5]
 [3 1]] [7 1]
[[6 5]
 [3 1]] [7 2]
[[6 5]
 [3 1]] [8 2]
[[6 5]
 [3 1]] [8 3]
[[6 5]
 [3 1]] [9 3]
[[6 5]
 [3 1]] [9 4]
[[6 5]
 [3 2]] [5 1]
[[6 5]
 [3 2]] [6 1]
[[6 5]
 [3 2]] [6 2]
[[6 5]
 [3 2]] [7 2]
[[6 5]
 [3 2]] [7 3]
[[6 5]
 [3 2]] [8 3]
[[6 5]
 [3 2]

[[7 3]
 [1 1]] [8 1]
[[7 3]
 [1 1]] [9 2]
[[7 3]
 [2 1]] [7 1]
[[7 3]
 [2 1]] [8 2]
[[7 3]
 [2 1]] [9 3]
[[7 3]
 [3 1]] [6 1]
[[7 3]
 [3 1]] [7 2]
[[7 3]
 [3 1]] [8 3]
[[7 3]
 [3 1]] [9 4]
[[7 3]
 [4 1]] [5 1]
[[7 3]
 [4 1]] [6 2]
[[7 3]
 [4 1]] [7 3]
[[7 3]
 [4 1]] [8 4]
[[7 3]
 [4 1]] [9 5]
[[7 3]
 [5 1]] [4 1]
[[7 3]
 [5 1]] [5 2]
[[7 3]
 [5 1]] [6 3]
[[7 3]
 [5 1]] [7 4]
[[7 3]
 [5 1]] [8 5]
[[7 3]
 [5 1]] [9 6]
[[7 4]
 [1 1]] [8 1]
[[7 4]
 [1 1]] [9 1]
[[7 4]
 [1 1]] [9 2]
[[7 4]
 [1 2]] [8 1]
[[7 4]
 [1 2]] [9 2]
[[7 4]
 [2 1]] [7 1]
[[7 4]
 [2 1]] [8 1]
[[7 4]
 [2 1]] [8 2]
[[7 4]
 [2 1]] [9 2]
[[7 4]
 [2 1]] [9 3]
[[7 4]
 [2 2]] [7 1]
[[7 4]
 [2 2]] [8 2]
[[7 4]
 [2 2]] [9 3]
[[7 4]
 [3 1]] [6 1]
[[7 4]
 [3 1]] [7 1]
[[7 4]
 [3 1]] [7 2]
[[7 4]
 [3 1]] [8 2]
[[7 4]
 [3 1]] [8 3]
[[7 4]
 [3 1]] [9 3]
[[7 4]
 [3 1]] [9 4]
[[7 4]
 [3 2]] [6 1]
[[7 4]
 [3 2]] [7 2]
[[7 4]
 [3 2]] [8 3]
[[7 4]
 [3 2]] [9 4]
[[7 4]
 [4 1]] [5 1]
[[7 4]
 [4 1]] [6 1]
[[7 4]
 [4 1]] [6 2]
[[7 4]
 [4 1]

 [4 6]] [5 1]
[[7 8]
 [4 6]] [6 2]
[[7 8]
 [4 6]] [7 3]
[[7 8]
 [4 6]] [8 4]
[[7 8]
 [4 6]] [9 5]
[[7 8]
 [5 1]] [9 1]
[[7 8]
 [5 2]] [8 1]
[[7 8]
 [5 2]] [9 2]
[[7 8]
 [5 3]] [7 1]
[[7 8]
 [5 3]] [8 2]
[[7 8]
 [5 3]] [9 3]
[[7 8]
 [5 4]] [6 1]
[[7 8]
 [5 4]] [7 2]
[[7 8]
 [5 4]] [8 3]
[[7 8]
 [5 4]] [9 4]
[[7 8]
 [5 5]] [5 1]
[[7 8]
 [5 5]] [6 2]
[[7 8]
 [5 5]] [7 3]
[[7 8]
 [5 5]] [8 4]
[[7 8]
 [5 5]] [9 5]
[[7 8]
 [5 6]] [4 1]
[[7 8]
 [5 6]] [5 2]
[[7 8]
 [5 6]] [6 3]
[[7 8]
 [5 6]] [7 4]
[[7 8]
 [5 6]] [8 5]
[[7 8]
 [5 6]] [9 6]
[[7 9]
 [1 2]] [9 1]
[[7 9]
 [1 3]] [8 1]
[[7 9]
 [1 3]] [9 1]
[[7 9]
 [1 3]] [9 2]
[[7 9]
 [1 4]] [8 1]
[[7 9]
 [1 4]] [9 1]
[[7 9]
 [1 4]] [9 2]
[[7 9]
 [1 5]] [8 1]
[[7 9]
 [1 5]] [9 1]
[[7 9]
 [1 5]] [9 2]
[[7 9]
 [1 6]] [8 1]
[[7 9]
 [1 6]] [9 1]
[[7 9]
 [1 6]] [9 2]
[[7 9]
 [1 7]] [8 1]
[[7 9]
 [1 7]] [9 2]
[[7 9]
 [2 2]] [9 1]
[[7 9]
 [2 3]] [8 1]
[[7 9]
 [2 3]] [9 1]
[[7 9]
 [2 3]] [9 2]
[[7 9]
 [2 4]] [7 1]
[[7 9]
 [2 4]] [8 1]
[[7 9]
 [2 4]] [8 2]

 [6 4]] [9 6]
[[8 7]
 [1 1]] [9 1]
[[8 7]
 [1 2]] [9 1]
[[8 7]
 [1 3]] [9 1]
[[8 7]
 [1 4]] [9 1]
[[8 7]
 [1 5]] [9 1]
[[8 7]
 [2 1]] [8 1]
[[8 7]
 [2 1]] [9 1]
[[8 7]
 [2 1]] [9 2]
[[8 7]
 [2 2]] [8 1]
[[8 7]
 [2 2]] [9 1]
[[8 7]
 [2 2]] [9 2]
[[8 7]
 [2 3]] [8 1]
[[8 7]
 [2 3]] [9 1]
[[8 7]
 [2 3]] [9 2]
[[8 7]
 [2 4]] [8 1]
[[8 7]
 [2 4]] [9 1]
[[8 7]
 [2 4]] [9 2]
[[8 7]
 [2 5]] [8 1]
[[8 7]
 [2 5]] [9 2]
[[8 7]
 [3 1]] [8 1]
[[8 7]
 [3 1]] [9 1]
[[8 7]
 [3 1]] [9 2]
[[8 7]
 [3 2]] [7 1]
[[8 7]
 [3 2]] [8 1]
[[8 7]
 [3 2]] [8 2]
[[8 7]
 [3 2]] [9 1]
[[8 7]
 [3 2]] [9 2]
[[8 7]
 [3 2]] [9 3]
[[8 7]
 [3 3]] [7 1]
[[8 7]
 [3 3]] [8 1]
[[8 7]
 [3 3]] [8 2]
[[8 7]
 [3 3]] [9 1]
[[8 7]
 [3 3]] [9 2]
[[8 7]
 [3 3]] [9 3]
[[8 7]
 [3 4]] [7 1]
[[8 7]
 [3 4]] [8 1]
[[8 7]
 [3 4]] [8 2]
[[8 7]
 [3 4]] [9 2]
[[8 7]
 [3 4]] [9 3]
[[8 7]
 [3 5]] [7 1]
[[8 7]
 [3 5]] [8 2]
[[8 7]
 [3 5]] [9 3]
[[8 7]
 [4 1]] [8 1]
[[8 7]
 [4 1]] [9 1]
[[8 7]
 [4 1]] [9 2]
[[8 7]
 [4 2]] [7 1]
[[8 7]
 [4 2]] [8 1]

[[9 5]
 [2 1]] [9 1]
[[9 5]
 [2 2]] [9 1]
[[9 5]
 [2 3]] [9 1]
[[9 5]
 [3 1]] [8 1]
[[9 5]
 [3 1]] [9 1]
[[9 5]
 [3 1]] [9 2]
[[9 5]
 [3 2]] [8 1]
[[9 5]
 [3 2]] [9 1]
[[9 5]
 [3 2]] [9 2]
[[9 5]
 [3 3]] [8 1]
[[9 5]
 [3 3]] [9 2]
[[9 5]
 [4 1]] [7 1]
[[9 5]
 [4 1]] [8 1]
[[9 5]
 [4 1]] [8 2]
[[9 5]
 [4 1]] [9 1]
[[9 5]
 [4 1]] [9 2]
[[9 5]
 [4 1]] [9 3]
[[9 5]
 [4 2]] [7 1]
[[9 5]
 [4 2]] [8 1]
[[9 5]
 [4 2]] [8 2]
[[9 5]
 [4 2]] [9 2]
[[9 5]
 [4 2]] [9 3]
[[9 5]
 [4 3]] [7 1]
[[9 5]
 [4 3]] [8 2]
[[9 5]
 [4 3]] [9 3]
[[9 5]
 [5 1]] [6 1]
[[9 5]
 [5 1]] [7 1]
[[9 5]
 [5 1]] [7 2]
[[9 5]
 [5 1]] [8 1]
[[9 5]
 [5 1]] [8 2]
[[9 5]
 [5 1]] [8 3]
[[9 5]
 [5 1]] [9 2]
[[9 5]
 [5 1]] [9 3]
[[9 5]
 [5 1]] [9 4]
[[9 5]
 [5 2]] [6 1]
[[9 5]
 [5 2]] [7 1]
[[9 5]
 [5 2]] [7 2]
[[9 5]
 [5 2]] [8 2]
[[9 5]
 [5 2]] [8 3]
[[9 5]
 [5 2]] [9 3]
[[9 5]
 [5 2]] [9 4]
[[9 5]
 [5 3]] [6 1]
[[9 5]
 [5 3]] [7 2]
[[9 5]
 [5 3]] [8 3]
[[9 5]
 [5 3]] [9 4]
[[9 5]
 [6 1]] [6 1]
[[9 5]
 [6 1]] [7 1]
[[9 5]
 [6 1]

[[9 8]
 [7 1]] [9 1]
[[9 8]
 [7 2]] [8 1]
[[9 8]
 [7 2]] [9 2]
[[9 8]
 [7 3]] [7 1]
[[9 8]
 [7 3]] [8 2]
[[9 8]
 [7 3]] [9 3]
[[9 8]
 [7 4]] [6 1]
[[9 8]
 [7 4]] [7 2]
[[9 8]
 [7 4]] [8 3]
[[9 8]
 [7 4]] [9 4]
[[9 8]
 [7 5]] [5 1]
[[9 8]
 [7 5]] [6 2]
[[9 8]
 [7 5]] [7 3]
[[9 8]
 [7 5]] [8 4]
[[9 8]
 [7 5]] [9 5]
[[9 8]
 [7 6]] [4 1]
[[9 8]
 [7 6]] [5 2]
[[9 8]
 [7 6]] [6 3]
[[9 8]
 [7 6]] [7 4]
[[9 8]
 [7 6]] [8 5]
[[9 8]
 [7 6]] [9 6]
[[9 9]
 [2 2]] [9 1]
[[9 9]
 [2 3]] [9 1]
[[9 9]
 [2 4]] [9 1]
[[9 9]
 [2 5]] [9 1]
[[9 9]
 [2 6]] [9 1]
[[9 9]
 [2 7]] [9 1]
[[9 9]
 [3 2]] [9 1]
[[9 9]
 [3 3]] [8 1]
[[9 9]
 [3 3]] [9 1]
[[9 9]
 [3 3]] [9 2]
[[9 9]
 [3 4]] [8 1]
[[9 9]
 [3 4]] [9 1]
[[9 9]
 [3 4]] [9 2]
[[9 9]
 [3 5]] [8 1]
[[9 9]
 [3 5]] [9 1]
[[9 9]
 [3 5]] [9 2]
[[9 9]
 [3 6]] [8 1]
[[9 9]
 [3 6]] [9 1]
[[9 9]
 [3 6]] [9 2]
[[9 9]
 [3 7]] [8 1]
[[9 9]
 [3 7]] [9 2]
[[9 9]
 [4 2]] [9 1]
[[9 9]
 [4 3]] [8 1]
[[9 9]
 [4 3]] [9 1]
[[9 9]
 [4 3]] [9 2]
[[9 9]
 [4 4]] [7 1]
[[9 9]
 [4 4]

In [178]:
w = np.array([[3,3],[1,1]])
b = np.array([4,1])

print(np.argmin(np.dot(w,x1)-b))
print(np.argmin(np.dot(w,x2)-b))
print(np.argmin(np.dot(w,x3)-b))
print(np.argmin(np.dot(w,x4)-b))

0
0
0
1
